[default]
extend-ignore-identifiers-re = [
    "Mmaped",
    "mmaped",
    "arange",
    "Nd",
    "nin",
]

[files]
extend-exclude = [
    "diffuse_rs_common/src/core/*",
    "diffuse_rs_common/src/nn/*",
    "diffuse_rs_common/src/cuda_kernels/*",
    "diffuse_rs_common/src/metal_kernels/*"
]